# Generated by Django 3.0.3 on 2022-01-17 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_ID', models.CharField(max_length=256)),
                ('domain_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism_taxa_ID', models.CharField(blank=True, db_index=True, max_length=256)),
                ('organism_clade_identifier', models.CharField(blank=True, max_length=256)),
                ('organism_scientific_genus_name', models.CharField(blank=True, max_length=256)),
                ('organism_scientific_species_name', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfam_domain_ID', models.CharField(max_length=256)),
                ('pfam_domain_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_ID', models.CharField(blank=True, max_length=256)),
                ('length_of_protein', models.IntegerField(blank=True)),
                ('domain_start_coordinate', models.IntegerField(blank=True)),
                ('domain_end_coordinate', models.IntegerField(blank=True)),
                ('domain_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.Domain')),
                ('organism_taxa_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.Organism')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='pfam_domain_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.Pfam'),
        ),
    ]
